### ISSUE TITLE
Goal amount is reset to the first digit

### ISSUE THREAD

**Issue by CoertvandenEnk** [Studio164a/appthemer-crowdfunding#2]
- After editing a campaign page, the goal is reset to the first digit. Instead of €2.750,- is becomes €3,- 

I suspect this is because of the period. If you change it to a 2,750 or 2750, that should work. I'm not sure if this issue could be resolved on the Easy Digital Downloads side or if it is an issue in the crowdfunding plugin. Could you test if you see this issue both when you edit the campaign on the frontend and when you edit it in the dashboard? 

2.750 becomes 3 as a result of its integer value probaly. If I set the 1000 delimiter to “.” this happens.
If I leave this field and the comma separator empty, it automatically inserts a “,” a a thousand separator
In the Netherlands we use no separator or the “.” as a thousand separator.

Any idea?

**Comment by ericnicolaas** [comment]
@CoertvandenEnk Sorry for not responding to you about this last year. We thought we had fixed this issue but it has reared its head again. Upon closer inspection, we've noted this is related to an issue in Easy Digital Downloads itself. Reported at https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3528

This issue should be resolved when that bug in EDD is fixed

Cheers, 
Eric
