### ISSUE TITLE
problem with crownfunding counters

### ISSUE THREAD

**Issue by filoago** [Studio164a/appthemer-crowdfunding#4]
We have problems with the counters on campaigns multi option in multi site wordpress.
We enabled the test mode and the gateway "paypal standard" and "Payment test".

Using "Paypal standard" payments are not completed and are waiting.
Using "test Payment" payments are completed but the counters are not updated and the widget does not show the participants.
We tried both Paypal IPN enabled and disabled.

At the moment the site does not have dns, but can be reached by setting the following rule in the hosts file:

176.9.94.218 vivi.passaggifestival.it

thanks

**Comment by ericnicolaas** [comment]
Thanks for the message. I saw your other email through our support form, so will respond to this there too.
