### ISSUE TITLE
Custom Pledging

### ISSUE THREAD

**Issue by Julian1936** [Studio164a/appthemer-crowdfunding#8]
Hello,

This is my first time commenting on an external project so please be kind!!

I am using this plugin but I can't seem to get the Custom Pledge part working is there an issue? Can you let me know how to set up the settings in order to get this working.

Thank you so much in advance.
Julian

**Comment by ericnicolaas** [comment]
Sorry @Julian1936, we are no longer supporting or developing this plugin.
