### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Florent73** [Studio164a/appthemer-crowdfunding#9]
Hi!

Thanks a lot for this plugin !

This is my contribution : French Translation

Download here : [http://restezconnectes.fr/plugins/atcf-fr_FR.zip]

**Comment by DaveRaul** [comment]
Hey,

I'm about to work on my own translation, but i can't enable it. Can you please tell me how you've enabled your translation?

**Comment by Florent73** [comment]
Hi!

I just put the files in the /appthemer-crowdfunding/languages/ folder ...

That's all !

**Comment by ericnicolaas** [comment]
@Florent73 Thanks for making a translation. We're not actively developing or supporting this plugin anymore though. You are more than welcome to fork the project and make it yours of course!
